### ISSUE TITLE
Can't choose singer

### ISSUE THREAD

**Issue by gdsjmksdgkksjgmd** [stakira/OpenUtau#1167]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

I can't choose any voicebank. Button doesn't working.

### Explains how to reproduce the bug

1. Open OpenUtau
2. Click on choose singer 
3. Nothing happening and no singer choose

### OS & Version

Windows 10, OpenUtau 0.1.327.0

### Logs

Idk

**Comment by oxygen-dioxide** [comment]
OpenUtau doesn't ship with singers. You should download one and install it before using.

**Comment by shellduck8** [comment]
> OpenUtau doesn't ship with singers. You should download one and install it before using. Which language do you want to sing in OpenUtau?

Hey, I have the same issue, I don't know where to download a simple English singer. As an addition, are there celeb voices? Like Micheal Jackson or someone else?

**Comment by Nexys4t** [comment]
> > OpenUtau doesn't ship with singers. You should download one and install it before using. Which language do you want to sing in OpenUtau?
> 
> Hey, I have the same issue, I don't know where to download a simple English singer. As an addition, are there celeb voices? Like Micheal Jackson or someone else?

Celebrity voices are illegal to use unless one of them made a voicebank for UTAU or OpenUTAU. The exception is someone else making a voicebank WITH PERMISSION from the celebrity. Alternatively you can make one yourself for those celebrities, but you wouldn't be able to distribute it since it's still illegal as long as you don't have their permission.

In the UTAU Wiki you have many voicebanks of any language. Do not be afraid of all the formats if you search for English voicebanks (VCCV for example) since OpenUTAU lets you write the words instead of phonemes in the notes as long as you choose the correct phonemizer.

**Comment by shellduck8** [comment]
> > > OpenUtau doesn't ship with singers. You should download one and install it before using. Which language do you want to sing in OpenUtau?
> > 
> > 
> > Hey, I have the same issue, I don't know where to download a simple English singer. As an addition, are there celeb voices? Like Micheal Jackson or someone else?
> 
> Celebrity voices are illegal to use unless one of them made a voicebank for UTAU or OpenUTAU. The exception is someone else making a voicebank WITH PERMISSION from the celebrity. Alternatively you can make one yourself for those celebrities, but you wouldn't be able to distribute it since it's still illegal as long as you don't have their permission.
> 
> In the UTAU Wiki you have many voicebanks of any language. Do not be afraid of all the formats if you search for English voicebanks (VCCV for example) since OpenUTAU lets you write the words instead of phonemes in the notes as long as you choose the correct phonemizer.

So, I don't have utau classic, but I want to know where to get those celeb voicebanks if they exist. The song is for personal use and experimenting, so I'm not distributing. Is there a way to make those  voicebanks from an RVC ai model I found.

**Comment by Nexys4t** [comment]
> So, I don't have utau classic, but I want to know where to get those celeb voicebanks if they exist. The song is for personal use and experimenting, so I'm not distributing. Is there a way to make those voicebanks from an RVC ai model I found.

As I said before, you cannot get them or have to make them yourself. And if you really want one, you will have to do some job crawling on the internet.

It doesn't matter that you don't have UTAU classic since OpenUTAU is compatible with the UTAU voicebanks.

It also doesn't matter if you're not distributing the song. It's still illegal if you ever release the voice for public usage.

There's people who made voicebanks with the help of RVC stuff, but it's a painful process in most cases.

As a final note, I suggest that you use user made voicebanks. OR try DecTalk Paul (I think that was the name) wich someone made an UTAU of (I'm not sure if there's an English voicebank, but I can search him for you).

**Comment by gdsjmksdgkksjgmd** [comment]
> OpenUtau doesn't ship with singers. You should download one and install it before using. Which language do you want to sing in OpenUtau?

I have some japanese voicebanks, like Gekiyaku and Kasane Teto. I had install them, but there no voicebanks in the list of vocalists

**Comment by gdsjmksdgkksjgmd** [comment]
I deleted strange file and there is no issues

**Comment by Nexys4t** [comment]
> > OpenUtau doesn't ship with singers. You should download one and install it before using. Which language do you want to sing in OpenUtau?
> 
> I have some japanese voicebanks, like Gekiyaku and Kasane Teto. I had install them, but there no voicebanks in the list of vocalists

Please try looking in the CLASSIC menu while choosing a singer or send a screenshot. Also make sure to update to the latest version if you haven't already?
