### ISSUE TITLE
Voice Color expression gives "error: out of range"

### ISSUE THREAD

**Issue by Zero-the-Fool** [stakira/OpenUtau#169]
**Describe the bug**
I've tried using the CLR expression multiple times, twice with Kasane Teto (once with the kanji for the colors, i.e. 囁,力,↑, the other time being just now with the English names, i.e. core,sasayaki,chikara,sakebi), and once with Kemonone Row Chain-Blaster, using the respective kanji (強,弱).

**To Reproduce**
1. Choose any UST/USTX, this behavior is universal
2. Make sure the CLR parameter has values listed in it.
3. Make sure the voicebank is multi-expressional
4. Use the CLR expression

**Expected behavior**
Displaying the respective colors in a list, and allowing the user to choose.

**Screenshots**
![image](https://user-images.githubusercontent.com/94862294/142913796-a7d5978f-be66-417d-b6e8-f42d5a3d158d.png)

**Environment:**
 - OS: Windows (Windows 10, if the specific version matters)
 - Version: 0.0.513.0/0.0.514.0
 - Voicebanks used: Kasane Teto (Core, Rikimi, Sakebi, Sasayaki)/Kemonone Row Chain-Blaster

**Comment by Zero-the-Fool** [comment]
This could also just be me using the expression wrong, but I figured I'd report it anyways.

**Comment by Penndemonium** [comment]
Hey! I was having a similar problem, so I looked it up and all I could find was this. Which, obviously, didn't help much since no solutions had been listed yet. Instead of waiting for one to appear I went back to the program and tried fiddling with it a bit more. And I found a solution! At least for the issue I was having. You have to configure the voice colors by going to "tools > singers", selecting the voice you're using, and hitting the "Edit Subbanks" button. You make a "color" for each subbank you want to use, select the pitch range that qualifies (unless it's pitched-based, just do "Select All"), and set either a prefix or a suffix! Then hit save at the bottom and you're good to go :) You need at least two colors in order for it to work, though.

I'm not sure how good my explanation is, so I'll also provide pictures of the "colors" I set up for Yokune Ruko ♂ (KIRE) and Kasane Teto!

![image](https://user-images.githubusercontent.com/94872693/142942822-cbf3aee1-e1f9-46c8-9492-1c462cec2f00.png)
"auto" is the usual automatic thing, but 0-3 is G#3, D#4, F#4, and B4 respectively for more finetuning.

![image](https://user-images.githubusercontent.com/94872693/142943733-466e9683-4d86-4676-8531-17b52348774a.png)
By the way, for the default bank color, set " " (space) as the suffix. If you don't, it won't save in the subbank list. Also, I'm aware I need to download more of Teto's banks, but I haven't gotten around to it yet.

Hope this helped!

**Comment by Zero-the-Fool** [comment]
This works! Thank you!
