### ISSUE TITLE
Still can't load a singer but for a different reason now.

### ISSUE THREAD

**Issue by 123happily** [stakira/OpenUtau#37]
It's me again :/ 

I appreciate the quick response to my last post. Something about my computer just doesn't like this program I guess.

I followed the same steps as last time and now I get this: 
![Capture](https://user-images.githubusercontent.com/77481373/105144757-a0019600-5b4d-11eb-863c-b400c095f1dc.PNG)

More details: I'm storing all openUTAU and UTAU related things on a secondary hard drive, not sure if that's a problem. It's wired in, just not the boot drive. The only account on this computer is an Admin one so I don't think permissions is the issue but I could be wrong.

Best of luck to y'all!

**Comment by stakira** [comment]
1. Does this happen to some voicebanks, or any of them? Where can I download these voicebanks?
2. What's your system language?

**Comment by 123happily** [comment]
1. It happened to a zipped (.zip) VCV bank in a 'singer' folder i made in the OpenUTAU file

I tried with another, different VCV bank that was still sitting zipped in my downloads and got this after some lag/time
![Capture](https://user-images.githubusercontent.com/77481373/105456788-afabe680-5cd5-11eb-8335-f97819ea564d.PNG)
If i take that same bank's zipped file (.rar) and put it in the 'singer' folder i get the same issue (no lag this time)
All of these banks are a little complex with multiple pitches/appends and bonus sounds, but i hope that's not the problem.

2. System _language_ is English but Japan locale since before installing UTAU. I have the Japanese IME keyboard too.

**Comment by LovelyA72** [comment]
Any follow-up on this issue? Seems like my #44 a duplication of this issue and I should close that issue.

**Comment by LovelyA72** [comment]
Here's my follow-up
Multiple issues are involved in this voicebank import issue
Issue 1: Zip path issue. As shown in the image, if the archive's root directory contains the data of the singer instead of a single folder that contains the data of the singer, the import will fail:
![image](https://user-images.githubusercontent.com/29054052/121792850-d658b400-cbc7-11eb-93b4-d428f1260178.png)
![image](https://user-images.githubusercontent.com/29054052/121792901-5e3ebe00-cbc8-11eb-91eb-b55454fd3699.png)

Issue 2: OpenUTAU also requires **valid** character.txt and readme.txt presents. Or it will also throw a user non-friendly exception(about string being null) and not let you import

Issue 3: The oto.ini file **MUST** encoded in Shift-JIS. A UTF-8 encoded oto.ini will cause an import failure

Issue 4: Alias are empty in the oto.ini file, although the import will success, the singer browser will not list any notes that are supposed to be in the oto.ini. There was a simular issue in UTSU(https://github.com/titinko/utsu/issues/11) that you can use as an reference.

**Comment by LovelyA72** [comment]
For issue 4, here's a simple python script for a quick fix to a broken _oto.json
```python
import os
import json

filePath = "(your_path)/_oto.json"

with open(filePath,"r") as r:
    data = json.load(r)
os.rename(filePath,filePath+".bak")
for i in range(0,len(data["Otos"])):
    data["Otos"][i]["Name"] = data["Otos"][i]["OrigWav"][0:-4]

with open(filePath, "w") as w:
    json.dump(data, w)

```

**Comment by stakira** [comment]
Thanks, @LovelyA72. Really appreciate your investigation. Issue 4 is fixed in 45860d8.

All the sound libs I've seen are shift-jis or plain ascii. Similarly, they always have a root directory. Issue 1 and 3 are expected behavior. For issue 2, OpenOtau only look for character.txt but not readme.txt. I have always found character.txt in the popular soundlibs. To be honest, I doubt your kashouryo.zip can be installed by Utau. But, of course for Utau you have the choice to manually extract the zip file.

It's true that without any clearly defined rules, it has been difficult for OpenUtau to be compatible with the sound libs out there. Thanks for your contribution. Please let me know if you have other findings in this area.

**Comment by 123happily** [comment]
@LovelyA72 Hi! Sorry to bother you. I've been busy converting KYE: poison VCV to match these rules (thanks SO MUCH by the way, I'm a total beginner when it comes to code so this is really helpful.). I have just two questions:

1. What's a 'valid' character.txt and readme.txt? His aren't in SHIFT-JIS though I did manage to convert the oto without any trouble... I'm getting a string related issue but I'm not sure where to go from here. They look normal to me.

2. With the file tree and arrangements, I moved  all of the sound files that were inthe main folder into their own folder called 'Extra' (because they looked like bonus files like glottal stops and stuff). Will that break any part of the utauloid or will he still function?

Thanks so much for your help!

**Comment by LovelyA72** [comment]
Question 1: a valid character.txt should be in Shift-JIS with all of the data filled
Question 2: That should be a standard feature for OpenUTAU to have. If it can do it, I suggest you open a ticket and ask if @stakira can add this feature. Without this feature a lot of voicebanks are unusable.

**Comment by stakira** [comment]
Voicebank installing and been redesigned and improved a lot.
