### ISSUE TITLE
Could you please keep OpenUtau Linux compatible?

### ISSUE THREAD

**Issue by ElonSatoshi** [stakira/OpenUtau#4]
Our userbase isn't that small, and I'm not a programmer, but from what I've seen, it's easier to port a program from Linux to Windows, than from Windows to Linux.

**Comment by Phundrak** [comment]
Hello,

From what I see, the code of OpenUtau is heavily based on the .NET Framework, which is not GNU/Linux compatible. Maybe some elements might be supported by the Mono Framework, but it is unlikely that the whole project is. And this issue is deeply rooted in this project due to the language used: C#. Had it been C++ or Java, it would have been “easier” to change the UI framework (it would still be very complex to do so), but there is close to no alternative for GNU/Linux and OS X/macOS when using the .NET Framework.
So, unless a brave programmer decides to convert all of the code to another language and port the UI to a cross-platform framework (such as C++ with Qt or Java with its own framework for instance), it is very unlikely to see OpenUTAU running on GNU/Linux, except maybe with wine (but there is not way of knowing if this will indeed work).
And if anyone could prove me wrong, I’d be damn glad to hear that.

Also, I would like to see OpenUtau running on GNU/Linux, but let’s be real for a moment: only about 2% on June 2017 of desktop and laptop users use GNU/Linux, and a good share of them dual-boot GNU/Linux with either Windows (84% on June 2017) or macOS (12% on June 2017). If any platform needs to be supported first after Windows it would be first OS X/macOS, then GNU/Linux.

I hope that answered your question.
(also side note: I’m currently looking at the code and discovering how it works and I’ll see if I might be able to help, I’m not really well versed in C#)

**Comment by stakira** [comment]
Sorry, it's heavily based on WPF technology, therefore not Linux compatible from the very beginning.

**Comment by skytetsu** [comment]
I was reading the framework and how to make it compatible, is framework 45, in monodevelop project has some part of the compatible
http://www.mono-project.com/docs/about-mono/compatibility/
"
C# 5.0 - async support
Async Base Class Library Upgrade
MVC4 - Partial, no async features supported.
MVC5 - Partial, no async features supported.
ASP.NET 4.5 Async Pipeline - Needs a parallel processing pipeline with async support, not done.
"
there are stuff i do not know, like if openutau use pipeline, there fore not compatible with monoproject who is make not easy to porting.  also if some of the partly features are used. when i try to run in monodevelop, it didn't run, saying "Not in the list of compatible projects"
Maybe need to debug a lot more, or a little more. Therefore there is much I don't know, but thats my two penny's.
