### ISSUE TITLE
OpenUTAU not playing NNSVS voicebanks

### ISSUE THREAD

**Issue by B3atrixP** [stakira/OpenUtau#551]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

When using an NNSVS voicebank, OpenUTAU has recently shown to not play the voicebank after rendering. Clearing caches does not fix the issue.
Note: This only affects certain voicebanks. 
 

### Explains how to reproduce the bug

EX:
Open ENUNU_server
Open OpenUTAU
Open .ustx file
Use AI voicebank
Press play

### OS & Version

Windows 11. OpenUTAU v0.0.991.0

### Logs

[log20221114.txt](https://github.com/stakira/OpenUtau/files/10007316/log20221114.txt)

**Comment by BagelHero** [comment]
This is late, but for ENUNU errors the ENUNU server log is often needed.
That said, I would presume that since this is singer specific you just needed to have an updated copy of ENUNU server. Some AI VBs need 0.5.1 and I think one or two need 0.6.0. 

Currently, you need to manually update the ENUNU server by making a copy of your currently functioning server folder, downloading [the appropriate release of ENUNU](https://github.com/oatsu-gh/ENUNU/releases) for the VB you want to use, and combining them. You need to _overwrite the ENUNU server files_ with the _regular_ ENUNU files.

I hope this helps others having this issue.
