### ISSUE TITLE
About the OpenUtau Discord Server

### ISSUE THREAD

**Issue by Astel123457** [stakira/OpenUtau#601]
### Acknowledgement

- [X] I have read Getting-Started and FAQ

### 🐛 Describe the bug

This is less about OpenUtau and more about the OpenUtau Discord server.

Long story short, we need more mods.

There have been multiple fights that have started that have gone on for a while with no interference from moderators.

StAkira is not on most of the time to stop fights when possible.

And the other two mods usually are not available.

I think we need at least 3 or so more mods, to be able to fill in the gap where the current mods are not able to, or at most 10.

We have a short list of people willing to become mods, these include:

Haru no Yuki (-aハルノユキ)
123Happily
hako
(Their Discord Names)

### Explains how to reproduce the bug

N/A

### OS & Version

N/A

### Logs

N/A

**Comment by HARUNOYUKIDAYO** [comment]
Harunoyuki Here, as person who has been attacked in the first major attack back in the end of last year and kinda was in the middle of the Karisu drama with a bunch of other unfortunate individuals as well as the person who was groomed by that individual for about 4 hours, I just have to say that I'd love to moderate for you so that I don't have to deal with that ever again thank you. Seriously

- to StAkira
