### ISSUE TITLE
Just a suggestion: ability to alternate resamplers for different notes

### ISSUE THREAD

**Issue by 123happily** [stakira/OpenUtau#73]
I’ve been following the development of this program for a little while and it’s looking seriously great. The only reason I haven’t made the switch is that default UTAU supports a plug-in which allows me to use TIPS (for example) on certain notes instead of my default resampler. This lets me manage end breaths to a higher quality.

I suppose if you wanted to render both strings/audio files simultaneously you could interpolate between them but that’s probably not smart performance wise.

This isn’t really an issue, just a suggestion, so feel free to delete it.

Thanks as always!

**Comment by unknownLinguist** [comment]
That'd be huge.  Either:  A) a way to call a resampler other than default for a given note, B) A "Rule" you set up in the project settings, or the voicebank's settings, such as _Default Resampler = X_, **and an optional rule(s)**; _Resampler for breaths (alone) = X_, _Resampler for notes containing breaths_, or even; "Custom group use resampler = X" (Like if you have a multipitch or vocal fry samples and a special engine for just the vocal fry).  

In fact since breath samples are a common headache, it'd be incredible if there was a quick and easy built in resampler, with the job of generating a breath sample in with appropriate blending from an attached phoneme.  Maybe that would be something the wavtool could handle?  idk im not a programmer I just like this idea.

**Comment by 123happily** [comment]
Thanks for the reply! It’s fascinating and a bit daunting to hear how many different ways this could work.

A) is how the plug-in I use currently works. It adds a ‘/2’ or ‘/#’ flag which calls a specific resampler, of which there are set options. It makes me feel like its a shortened version of a file path, honestly. And yes VCV is super annoying with long cross fades, I use constant velocity to try to minimise the effect. That’s the only reason I suggested a crossfading option.

B) This also sounds alright for convenience (set a preferred resampler for a bank) but I’m not sure how easily it’ll give you note-by-note control. You could make a custom flag for it potentially where it just goes between 0 (main resampler) and 1 (secondary resampler)? I don’t know if you could then work in crossfades later but there is a workaround (consonant speed) so it’s not crucial.)

Other method) this sounds really interesting and if it could work it would be fantastic. I wonder if you’d be able to specify ‘vocal fry samples in this bank look like this, use this resampler’. As so many banks alias this stuff differently (I’ve seen E and ‘ options for vocal fry alone, and some banks just build it into the starting note). Definitely possible for in and out breaths. But, I’d still like the ability to override the preset as sometimes breath sounds come out awful in TIPS and great in like, fresamp.

Loved reading your comment, hopefully we can figure out the most streamlined and flexible solution before anyone has to code anything :)

**Comment by stakira** [comment]
Did not realize this issue is here. Added yesterday: https://github.com/stakira/OpenUtau/wiki/Getting-Started#eng-resampler-engine
