### ISSUE TITLE
Can u make the Android(for mobile

### ISSUE THREAD

**Issue by sansko** [stakira/OpenUtau#968]

**Comment by oxygen-dioxide** [comment]
- It's theoretically possible to port OpenUtau to mobile platforms. OpenUtau is written in [dotnet](https://dotnet.microsoft.com), and there are several dotnet cross-platform UI frameworks for mobile.
- Mobile operating systems and user experiences are different from desktop's, which requires a fully UI-redesign and rewrite. OpenUtau is an open-source software. Unlike commercial softwares, OpenUtau is developed by community in their spare time. Development bandwith is limited. However, since the source code is public, anyone can implement their ideas.
- There are still many limitations. Android doesn't support exe, which means that you can't use third-party resamplers or wavtools on Android, such as Moresampler. NNSVS, originally written in python, would need a fully C# port before running on Android. Only Worldline-R and vogen would be supported.

**Comment by sansko** [comment]
please try your best

**Comment by vocoder712** [comment]
A developer ported OpenUtau to mobile: https://github.com/vocoder712/OpenUtauMobile
